### ISSUE TITLE
Groovy upsert nested script no longer working on 1.4.4

### ISSUE THREAD

**Issue by phil2396** [elasticsearch/elasticsearch#10019]
Hello,

I am using the bulk processor with the Update API of the ElasticSeach Java package. I'm running an upsert script which inserts records within a nested field of a document.

"if (ctx._source.records.contains(data)){ctx.op='none'; }else {ctx._source.records+=data;}"

I am running the following script on a 1.4.2 cluster and it works perfectly using the 1.4.4 client Java API.

However since I have upgraded on the new 1.4.4 ElasticSearch Cluster Server, the script is no longer working, documents are not deleted and reindexed. I think that might be related to the groovy modifications that were made in 1.4.3 server.

Thank you

**Comment by dakrone** [comment]
@phil2396 do you have the error or exception that you are getting back from Elasticsearch when you use the update API?

Dynamic scripting for Groovy was disabled in 1.4.3, which may be what you are seeing.

**Comment by phil2396** [comment]
@dakrone I don't see any errors from elasticsearch using the Update API. I will follow the procedure here http://www.elasticsearch.org/blog/running-groovy-scripts-without-dynamic-scripting/ and see if that fixes the issue.  I update later today. 

Thank you

**Comment by phil2396** [comment]
Using the Java API 1.4, I cannot specify file parameter to use the script on disk.

= > UpdateRequest.java

@dakrone

**Comment by dakrone** [comment]
@phil2396 you should be able to use `UpdateRequestBuilder` for this:

```java
client().prepareUpdate("index", "type", "id").setScript("scriptname", ScriptService.ScriptType.FILE).get();
```

**Comment by phil2396** [comment]
Thank you 

@dakrone

**Comment by femaffioletti** [comment]
Hi Phil, I'm facing the same problem. How did you resolve this? Just with the 'enabling dynamic scripting'?

Thanks for the help!!

**Comment by phil2396** [comment]
Hello @femaffioletti 

yes i solved it using dynamic scripting :)

**Comment by femaffioletti** [comment]
Mine is still nor working, I have this code in 1.3.4 version and Works perfectly, in the 1.4.4 even with the dynamics script enable and the script.groovy.sandbox.enabled enabled too it's not working with a strange error:

Caused by: org.elasticsearch.script.groovy.GroovyScriptCompilationException: MultipleCompilationErrorsException[startup failed:
Script2.groovy: 1: expecting '}', found ':' @ line 1, column 82.
   e.boUtilizado = [{"fkContagem":"6558","f
     
if (ctx._source["bo"] == null) {ctx._source.bo = [{"fkC":"6558","fkU":"55007946988"}]} else {ctx._source.bo += [{"fkC":"65358","fkU":"55007946988"}]}

it looks like an sintax error but in the older version this worked.
