### ISSUE TITLE
 expand_wildcards not accepted by /_cluster/state as advertised

### ISSUE THREAD

**Issue by HonzaKral** [elasticsearch/elasticsearch#5229]
As per documentation (0) all APIs that support multi-index also support expand_wildcards parameter, that is not the case with at least /_cluster/state:

    curl -X PUT localhost:9200/test_index
    {"acknowledged":true}
    curl -X POST localhost:9200/test_index/_close
    {"acknowledged":true}
    curl localhost:9200/*/_settings?expand_wildcards=closed
    {"test_index":{"settings":{"index":{"uuid":"CkMTVYfhS12TmHrWrNSkfQ","number_of_replicas":"1","number_of_shards":"5","version":{"created":"2000099"}}}}}
    curl localhost:9200/_cluster/state/metadata/*?expand_wildcards=closed
    {"cluster_name":"es_client_test","metadata":{"templates":{},"indices":{}}}

0 - http://www.elasticsearch.org/guide/en/elasticsearch/reference/current/multi-index.html

**Comment by cbuescher** [comment]
Since I just looked at IndicesOptions in another issue and start to get to know the rest apis a little bit I can look into this.

So far I think the ClusterStateRequest has no way to set IndicesOptions other than the default one (here LENIENT_EXPAND_OPEN) which does not expand wildcards. I could add overwritting these parameters with the request parameters like in e.g RestIndicesStatsAction, but for this I would need to introduce setter and internal field for indicesOptions in ClusterStateRequest. 

Most of the index-related actions inherit this from BroadcastOperationRequest, but since the ClusterStateRequest extends MasterNodeReadOperationRequest, theres no such setter / internal field here. Wondering where to put it. If the "expand_wildcard" parameter is supposed to work for all Cluster-related commands, then I think it should be somewhere higher up in the hierarchy.

**Comment by cbuescher** [comment]
I just saw that ClusterSearchShardsRequest is doing the same thing I would do in  ClusterStateRequest:

    private IndicesOptions indicesOptions = IndicesOptions.lenientExpandOpen();
    public ClusterSearchShardsRequest indicesOptions(IndicesOptions indicesOptions)

**Comment by javanna** [comment]
Hey @cbuescher what you proposed sounds good to me, let's add the ability to set `IndicesOptions` to `ClusterStateRequest`.

**Comment by cbuescher** [comment]
From reading the documentation above on multi-index parameters I guess that also "ignore_unavailable" and "allow_no_indices" should work here. Do I just add them to the cluster.state.json and write some test for them or does that make no sense here?

**Comment by javanna** [comment]
@cbuescher yes you got it right, those params need to be added to the spec and some tests for them would be appreciated ;)
