### ISSUE TITLE
Issue when applying nested aggregation and nested filter

### ISSUE THREAD

**Issue by rbnacharya** [elasticsearch/elasticsearch#7805]
Consider a scenario.
I've a mapping like this, 

    PUT /x1/x4/_mapping
    {
      "x4": {
        "properties": {
          "playerYears": {
            "type": "nested",
            "properties": {
              "schoolsOfInterest": {
                "type": "nested",
                "properties": {
                  "name": {
                    "type": "string",
                    "index": "not_analyzed"
                  }
                }
              },
              "rating": {
                "type": "float"
              }
            }
          }
        }
      }
    }

Consider simple data, 

    POST /x1/x4/1
    {
      "playerYears": {
        "rating": 10,
        "schoolsOfInterest": {
          "name": "x"
        }
      }
    }

And, When I apply filter like below,

    POST /x1/x4/_search
    {
      "size": 0,
      "aggs": {
        "rating": {
          "nested": {
            "path": "playerYears"
          },
          "aggs": {
            "rating-filtered": {
              "filter": {
                "nested": {
                  "path": "playerYears.schoolsOfInterest",
                  "query": {
                    "match_all": {}
                  }
                }
              }
            }
          }
        }
      },
      "query": {
        "match_all": {}
      }
    }

Then result is zero for `rating-filtered` aggregation. 

I am not able to figure it out why, can anyone help ?

**Comment by martijnvg** [comment]
I would expect that @rbnacharya example to work too, but the issue is that the `nested` filter is unaware of the fact it is wrapped in a `nested` aggregator and therefor assumes it needs to translate the nested hits to root (non nested) hits. The nested query simply doesn't get the context it is in from the `nested` aggregator. This is different then when a `nested` query/filter is wrapped in another `nested` query/filter, in that case the wrapped `nested` query is aware of the fact it is wrapped by a parent `nested` query/filter.

Due to the structure of the `nested` aggregator and the streaming parsing fixing this issue is tricky. One can define the request so that the child agg appears first:
```
{
  "aggs": {
    "rating": {
      "aggs": {
        "rating-filtered": {
          "filter": {
            "nested": {
              "path": "playerYears.schoolsOfInterest",
              "query": {
                "match_all": {}
              }
            }
          }
        },
        "nested": {
           "path": "playerYears"
        }
      }
    }
  },
}
```

So event if we did pass the nested context to the nested filter in the above case nothing would be passed, because the nested options have not been parsed yet.

I think the example that @clintongormley shared is a clearer way to define what @rbnacharya is after, because that example only makes used of `nested` aggregator and doesn't mix it with `nested` filter. One can still wrap the filter in the `rating-filtered` agg, that uses a term or range filter.

That said I think the best way to improve here is to add more validation. In this case the nested agg was expecting docs on the `playerYears` level while the nested filter was production root (non nested) documents as hits. ES should fail here, so that it is clear that the query defined is producing incorrect results (instead of returning 0 count as result).

I think this validation should not just be for the nested query/filter, but also for the nested aggregation and nested inner hits. Lets say one wraps two `nested` inner aggregations, but the `path` of the second `nested` aggregator is invalid, because it doesn't fall under the `path` of the first `nested` aggregator, it would good to fail. I'll open an issue for that.
