### ISSUE TITLE
Remove custom posting formats

### ISSUE THREAD

**Issue by clintongormley** [elasticsearch/elasticsearch#8746]
Custom posting formats (eg pulsing, direct, etc) are not supported by Lucene - they provide no bwc promise.  We removed the documentation before 1.4.0.Beta1, and we should prevent users from using these codecs going forward.

At the very least, we should deprecate custom codecs and refuse to create new indices that use them.  I don't know how widely used these are (I'd imagine not very widely at all), but I'd be tempted to remove them completely in 2.0.

**Comment by jpountz** [comment]
+1 to remove them completely. Given that they are not backward compatible anyway, even if we kept it there would be a high chance that loading the index would fail.

**Comment by bleskes** [comment]
just to clarify, we do plan to keep the ability to inject custom written codes/posting formats from plugins, right?

**Comment by jpountz** [comment]
I don't think we should.

**Comment by rmuir** [comment]
+1 Adrien. I also don't think the default codec of lucene needs to support such extensibility.

**Comment by s1monw** [comment]
+1 lets get rid of all this.

**Comment by bleskes** [comment]
We discussed it and it was my understanding that due to *dangerous* nature of replacing codecs, we are going to remove the ability to add custom one through the settings and plugins. It will still be possible to use lucene's SPI to add codecs on the lucene level, in which case one can use them via the index.code settings. I'm +1 on that.

To be clear, what I care about is removing all options to specific custom postings lists. I would be OK with not allowing to replace codecs but rather have other methods to add custom java level posting lists.

**Comment by jpountz** [comment]
@s1monw I'll take care of it.

**Comment by javanna** [comment]
this was not merged after all, right @brwe ?
