### ISSUE TITLE
Odd shard distribution in Elasticsearch 1.4.2

### ISSUE THREAD

**Issue by vichargrave** [elasticsearch/elasticsearch#9023]
I'm using a 4 node Elasticsearch cluster to ingest tweets from one of the public Twitter streams.  After upgrading my from 1.3.2 to 1.4.2 I'm noticing an odd behavior with respect to how shards are distributed across the nodes.  Whereas with 1.3.2 the 5 primary shards and 1 replica set of shards were evenly distributed across all 4 nodes, now I'm seeing this behavior:

1. All the primary shards are saved to one node
2. The replicas are split between two other nodes
3. The fourth node receives no shards at all

I'm using default values for these settings:

cluster.routing.allocation.balance.shard
cluster.routing.allocation.balance.index
cluster.routing.allocation.balance.primary
cluster.routing.allocation.balance.threshold

However I've set cluster.routing.allocation.balance.shard to 0.6f and cluster.routing.allocation.balance.primary to 0.06f in the hope that these settings will coerce Elasticsearch to distribute the shards more evenly.   

Is this issue a bug?

**Comment by vichargrave** [comment]
I think this should be logged as a bug. This is not a desirable behavior and it tempts me to roll back to 1.3.2.

**Comment by s1monw** [comment]
why are you setting `cluster.routing.allocation.balance.primary: 2.0f` you should not modify these settings. Did you have them set before? I don't necessarily see this as a bug. We might have some disbalance due to a rolling upgrade, how did you upgrade and did you disable allocation? is the rest of your cluster well balanced?

**Comment by vichargrave** [comment]
I'm trying to get the shards evenly distributed between the nodes in my cluster as they were in version 1.3.2.  I tried a rolling upgrade from 1.3.2 to 1.4.2, which is when this issues appeared.  Now, as I stated before I have a node with no data on it do 25% of my cluster's disk capacity is unused.  That can't be right if that is what Elasticsearch is doing, so yes it is a bug as far s I'm concerned.

Please review the previous posts which tell the entire story.

**Comment by s1monw** [comment]
I did read the post and the story, there are still some things I don't understand. Bare with me and help me to understand:

 - you have only one index in your cluster and one node has no shards of this index so 25% of your cluster is unused assumig 4 nodes, is this correct?
- if you have more indices are all of these indices well balanced or are there some indices that are not fully balanced?
- if you look at your cluster, is it balanced based on the number of shards per node cluster wide not per index?
- you set `cluster.routing.allocation.balance.primary` and `cluster.routing.allocation.balance.shard` did you also set `cluster.routing.allocation.balance.index`? if you didn't I think what you are seeing is expected or rather possible. if you want to have well balanced indices  you should give more weight to `cluster.routing.allocation.balance.index` and `cluster.routing.allocation.balance.primary` should really only be a tie-breaker.  It's pretty hard to get back to full balance if you have many indices that are not well balanced since the shard allocator was build to be conservative with respect to relocations.

I'd start with restoring defaults for these values:

```
cluster.routing.allocation.balance.primary: 0.5
cluster.routing.allocation.balance.shard: 0.45
cluster.routing.allocation.balance.index: 0.5
```
and calling `_reroute`

**Comment by s1monw** [comment]
FYI I just fixed the wrong default in my last comment from: `cluster.routing.allocation.balance.primary: 0.5` to `cluster.routing.allocation.balance.primary: 0.05`

**Comment by vichargrave** [comment]
No I have hundreds of indices.  Look at the previous settings out put I
posted when Clinton was answering my questions.   The graphic I induced was
just the result of a recent index.  I see what you mean about the
cluster.routing.allocation.balance.index field.  I have it set to the
default.  I experimented with the cluster.routing.allocation.balance.primary
 and cluster.routing.allocation.balance.shard settings according to
Clinton's suggestions.  There seems to be some confusion on this balancing
issue.

I'll set the fields you indicate back to their defaults.  I'm not sure what
you mean about then call _reroute.  I know how to omove shards around, but
what just to make sure we are talking about the same thing, what is the
_reroute call I should use?

**Comment by s1monw** [comment]
ok so if you have that many indices I can totally see how this can happen with the settings. Did you have any of these settings changed before this issue happened? 

> I'll set the fields you indicate back to their defaults.  I'm not sure what
you mean about then call _reroute.  I know how to omove shards around, but
what just to make sure we are talking about the same thing, what is the
_reroute call I should use?

I am referring to `http://www.elasticsearch.org/guide/en/elasticsearch/reference/current/cluster-reroute.html` if you call 

```
curl -XPOST 'localhost:9200/_cluster/reroute' -d '{}`
```

we do a rebalance run so you changes should kick in after that call. The pure update call won't trigger a reroute.

**Comment by vichargrave** [comment]
No I did not change any of the default settings.  That came later when I
noticed the problem.  Let me restore the default settings, then I'll give
the reroute call a try.  I'll keep you posted.

Many thanks.

**Comment by s1monw** [comment]
I am curious, would it be possible to get an output of the CAT API for shards: 
`http://www.elasticsearch.org/guide/en/elasticsearch/reference/current/cat-shards.html`
I wanna try to simulate the situation you are in that might give me a better insight into the shard allocation. It might be that the allocator has numerical problems with lots of shards and low number of nodes?

**Comment by vichargrave** [comment]
So I need to do this on each node, correct?

**Comment by s1monw** [comment]
> So I need to do this on each node, correct?

no, any node will do.

**Comment by vichargrave** [comment]
This a really long file.  Can I send it to you directly via email?

**Comment by s1monw** [comment]
sure `simon at elasticsearch DOT com`

**Comment by s1monw** [comment]
FYI @vichargrave I found the issue. It's in-fact a bug which can put your cluster in quite bad state. I opened a pull-request for it. ^^ 

Thanks for your input and patience! Once I have this committed to 1.4.x would you be able to verify the fix on your real cluster?

**Comment by vichargrave** [comment]
Yes I would be happy to.

-- vic

**Comment by s1monw** [comment]
cool I will keep you posted

**Comment by s1monw** [comment]
@vichargrave I pushed the fix to 1.4 and 1.3 as well. Do you have a chance to test this? Note, if you are are upgrading to a snapshot build you might not be able to revert back to 1.4.2! Please consider this, I don't know what purpose your cluster has or if you are running in production. I can totally understand if you say `no thanks`... if you can deal with it I'd be happy if you can try it out.
You also need to be aware that if you move to this new build you might see quite some relocations happening, in my tests I saw about 5% of your shards got relocated to get back balance in the cluster.

if you wanna simualte it I have a tests checked in :)

**Comment by vichargrave** [comment]
OK , so by I might not be able to revert back to 1.4.2, what does that
mean.  Would I be able to revert back to anything, 1.3.2, etc?  Also, if
the upgrade to the new code is successful, will all the shards on my
cluster be redistributed automaltically or do I still have to do that by
calling _reroute?

**Comment by s1monw** [comment]
oh ok so for `1.4.3-SNAPSHOT` you can downgrade to `1.4.2` since they have the same lucene version. You can't go back to `1.3.2` you will likely index too new exceptions. If you are doing a rolling restart I suggestion you to upgrade the non-master nodes first. once they all come up everything should rebalance automactially. Be aware it might take a while...

**Comment by vichargrave** [comment]
I checked out the code from github, but I don't see a 1.4.3-SNAPSHOT.
Perhaps I would be better off rolling back to back to 1.3.2 until the fix
goes into the mainstream code.  Also I'm more comfortable upgrading from
RPMs.

**Comment by vichargrave** [comment]
OK I decided to go ahead an build the 1.4.3-SNAPSHOT.  So I just
replace elasticsearch-1.4.2.jar
with 1.4.3-SNAPSHOT.jar correct?  Before I do that I'd like to review the
steps for an upgrade.  Here are the steps from your website:


   1. If possible, stop indexing new data. This is not always possible, but
   will help speed up recovery time
   2.

   Disable shard allocation. This prevents Elasticsearch from re-balancing
   missing shards until you tell it otherwise. If you know the maintenance
   will be short, this is a good idea. You can disable allocation with:

   PUT /_cluster/settings
   {
       "transient" : {
           "cluster.routing.allocation.enable" : "none"
       }
   }

   3.

   Shutdown a single node, preferably using the *Shutdown API* on that
   particular machine:

   POST /_cluster/nodes/_local/_shutdown

   4. Perform maintenance/upgrade
   5. Restart node, confirm that it joins the cluster
   6. Repeat 3-5 for the rest of your nodes
   7.

   Re-enable shard allocation using:

   PUT /_cluster/settings
   {
       "transient" : {
           "cluster.routing.allocation.enable" : "all"
       }
   }



In step 2, shouldn't the "transient" be changed to "persistent" because
when the node is restarted it will start tor rebalance, correct?

Please advise.

**Comment by s1monw** [comment]
sorry for the long delay I would not replace the jar file. I'd download a real package from `https://oss.sonatype.org/content/repositories/snapshots/org/elasticsearch/elasticsearch/1.4.3-SNAPSHOT/` you can get a `.deb`, `.zip`, or`.tar.gz` and do a real install on each node. 


> In step 2, shouldn't the "transient" be changed to "persistent" because
when the node is restarted it will start tor rebalance, correct?

since you are doing a rolling restart (cluster is always up) you can use transient. 

Note: you will see balancing going on once the master is upgraded and your cluster has allocated all shards that where there before ie. all indices are active.

**Comment by s1monw** [comment]
any updates on this? @vichargrave

**Comment by vichargrave** [comment]
Not quite yet.  I'll be pulling the trigger in a couple of days.

**Comment by vichargrave** [comment]
Hi Simon.

Something weird happened.   I have not yet tried the ES 1.4.3 snapshot you
provided, but when I deleted about half of the data we ingested, my cluster
spontaneously redistributed the shards evenly across the cluster.  We are
not talking about a lot of data - it's about 750 GB.  Do you know what
might have caused this?

So I'm not sure what to do now.  I'm disinclined to apply the patched build
since the cluster is in  state I wanted all along.

Let me know your thoughts when you get a chance.

-- vic

**Comment by vichargrave** [comment]
OK it looks like 1.4.2 is still not putting shards one of my 4 nodes.
After the data deletion though, it is another node that is avoided.  So I'm
going to try the patch soon.

-- vic

**Comment by orenorg** [comment]
Hello,
I'm also having a similar issue. Perhaps it's related.
Using version 1.4.1, using 2 nodes,total of 90 indexes ,2 shards for each, loading with 0 replicas and then updating to 1 replica after loading completes.

It appears that after a node restart/recovery most of the primary shards are located on the same node and the other node has most of the replicas respectively. Therefore, when creating a new index with 0 replicas, it puts all  shards (which are obviously primary) on the same node, the one with more replicas, causing the cluster not to use the other node for the loading process.

Tried fixing it by setting the below setting but that didn't  work:
cluster.routing.allocation.balance.index: 0.9f
cluster.routing.allocation.balance.shard: 0.0f
* to make sure it only cares about shard distribution within an index.

Since cluster.routing.allocation.balance.primary was deprecated since 1.3.8, I can't think of anyway to rebalance  the primary shards.
My only solution at this point is to index with 1 replica from the beginning...

Any thought?

**Comment by vichargrave** [comment]
Just wanted to follow p to let you kmow that I upgraded to 1.4.3.  After
re-starting the system the shards were all rerouted so they are now evenly
distributed across my four nodes.  All is well again.

**Comment by tnine** [comment]
Should this be fixed in 1.4.3?  We're also experiencing this issue.  I've added the following config to our yaml to ensure we're correct.


```
cluster.routing.allocation.balance.primary: 0.05
cluster.routing.allocation.balance.shard: 0.45
cluster.routing.allocation.balance.index: 0.5
```

Then hit this endpoint

```
curl -XPOST 'localhost:9200/_cluster/reroute' -d '{}'
```

Does this need to be run on the master node or will any node suffice?  I have 87 indexes in our cluster, each one has 6 shards, and 1 replica. We have 6 nodes in our cluster.  When I perform the rebalance, I'm still getting some nodes that have 4 primary shards.  This is causing very uneven load, and some of our applications are suffering significant performance degradation as a result.    Note that we applied the setting and restarted after disabling allocation.


```
$ curl -XPUT 'http://localhost:9200/_cluster/settings' -d '{
    "transient" : {
        "cluster.routing.allocation.disable_allocation": "true"
    }
}'
```

**Comment by vichargrave** [comment]
Hi Todd.

I reported this as a bug to Elasticsearch when I first upgraded to 1.4.2
two months ago.  Elasticsearch verified it was indeed a bug and fixed it in
1.4.3.  I verified this over the weekend when I upgraded to 1.4.3.

Good news is, when you upgrade to 1.4.3 it will automatically reroute your
shards so they are evenly distributed across your cluster.

-- vic

**Comment by tnine** [comment]
Hey @vichargrave 

Thanks for the response.  I'm able to rebalance shards manually via move, but running the rebalance command has no effect.  I have 12 shards as a test in a 6 node environment.  Where everything balanced evenly, I would expect 2 primaries per node.  Instead, I have 4 primaries in 1 node, and 3 in 2 others, causing some strange load profiles.  Is there another setting that could possibly be blocking shard-reallocation?  I receive no errors in the logs, and the HTTP call returns successfully.

**Comment by vichargrave** [comment]
You won't necessarily get 2 primaries per node.  You'll get a mixture of
primary and replica shards on any given node in your cluster.  If you see
shards on all your nodes for any given index then you are OK.  However, if
you see that a node consistently gets no shards, then you have the problem
I saw.

**Comment by tnine** [comment]
Thanks @vichargrave.  It appears we don't have the same issue, I'll move this to the mailing list.

**Comment by s1monw** [comment]
@tnine this is a common misunderstanding that the primaries are balanced across the cluster. The primary has to do the same amount of work as any other shard but it's the first one doing it. Balancing based on this is not necessary. we used it as a tie-breaker but removed the primary factor due to this misunderstanding. Are you using upsert / update api by any chance?

**Comment by francoisforster** [comment]
I found that the node that is the primary for all shards for my index is using more CPU, has slower search response times and uses more memory. I would benefit from having primaries balanced.

**Comment by tnine** [comment]
@s1monw Correct, however, what happens when there are 0 replicas?  This case, the primary shard is the only shard doing work.  If there are no replicas, I would expect the primary shards to be evenly distributed across the cluster per index.  Otherwise, nodes with more than 1 primary shard are going to receive increased traffic when there are no replicas to replicate data to.  We're seeing this in production now.
