### ISSUE TITLE
Expose logger object in the scripts

### ISSUE THREAD

**Issue by Vineeth-Mohan** [elasticsearch/elasticsearch#9068]
It might be required to log the events for a user from inside his script . Though this is very much possible in java native script , it might not be possible to other langauge.
So please expose a variable like doc or _source that can be used to log.

**Comment by clintongormley** [comment]
thanks @markharwood - could you provide a short example and then close this issue?

**Comment by markharwood** [comment]
Here's an example call out to a logger:

      "aggregations": {
		  "debug":{
			  "terms":{
				  "script":"import  org.elasticsearch.common.logging.*; ESLogger logger=ESLoggerFactory.getLogger('myscript'); logger.info('This is a log message'); return doc['myField'].value;"
			  }
		  }
		}

To enable the sandbox for the above script you'll need to set this in the configuration:

    script.groovy.sandbox.receiver_whitelist : org.elasticsearch.common.logging.ESLoggerFactory,org.elasticsearch.common.logging.ESLogger,java.lang.Object

Note that the above whitelist replaces rather than supplements the default list of permitted classes which is why I had to include a reference to java.lang.Object before the script would work. Your scripts may need access to more classes depending on what they do.

**Comment by q11112345** [comment]
@markharwood  how to set the log level in querying json code to the logging object in script?
