### ISSUE TITLE
Clarification on setTimeout and isTimeout Java API methods

### ISSUE THREAD

**Issue by ppf2** [elasticsearch/elasticsearch#9092]
Consider the following example of intentionally setting the query timeout value in the Java API to a very small number:

```
  SearchResponse sres = client.prepareSearch("index_name")
                    .setTimeout(TimeValue.timeValueNanos(1))
                    .addAggregation(AggregationBuilders.terms("id").field("id").size(1000).shardSize(1000))
                    .execute()
                    .actionGet();
            System.out.println("Is query timed out? " + sres.isTimedOut());
```

The query returns in > 1 nanosecond, but the isTimedOut parameter is false.  Would like to get a clarification on this.  Should isTimeOut return true in this case?  Or does it not return true because of the following enhancement request (https://github.com/elasticsearch/elasticsearch/pull/4586) to actually terminate queries that exceed the query timeout?

**Comment by markharwood** [comment]
The existing timeout checks are based on Lucene's TimeLimitingCollector which has settings measured in milliseconds so the granularity of your timer (1 nanosecond) may well be the issue here - it probably doesn't make sense to expect timeout logic to behave with settings of sub-millisecond.

Generally speaking, the accuracy of timeout checks is not as good as it could be and https://github.com/elasticsearch/elasticsearch/pull/4586 is all about introducing more frequent checks for overruns than the one provided by Lucene's TimeLimitingCollector. This requires a careful balance of improving early termination of bad queries without slowing search speeds of good queries with additional timer checks.

There will be no change to the client interface - just improved detection of overruns.

**Comment by clintongormley** [comment]
Closing in favour of #4586
