### ISSUE TITLE
De-duplication during indexing

### ISSUE THREAD

**Issue by c2h5oh** [elasticsearch/elasticsearch#9131]
### Problem
Right now to prevent duplicates in index you have two options:
- generate id based on document content in your application. Problems:
  * simple methods (md5 checksum of field or fields for example) work only with 1:1 matches
  * more complex methods require document processing and that forces you to duplicate parts of ES in your app (stemming, stopwords etc) and even then you only detect a duplicate if end result matches 1:1 whatever you have in ES

- search for each document in ES before inserting it. Problems:
  * doesn't work with bulk inserts (and is unusable in many places just because of this)
  * at least doubles item-by-item insert time (2 separate requests)
  * isn't atomic

### Possible solution
Feature similar to Solr de-duplication https://cwiki.apache.org/confluence/display/solr/De-Duplication
but instead of simple signatures offered by Solr, something using https://github.com/larsga/Duke (or parts of it)
There is already a plugin doing this for search https://github.com/YannBrrd/elasticsearch-entity-resolution

**Comment by clintongormley** [comment]
Hi @c2h5oh 

That entity-resolution plugin is interesting - I wasn't aware of it.  I've added it to the plugins page.

Deduplication is, obviously, an intensive and complex process  There is no magic lightweight solution - however you do it, you end up using the techniques that you describe in the issue description.

While we provide tools for finding similar documents (eg the more like this API, the significant terms aggregation, etc), it feels like a full deduplication framework should be part of the ETL pipeline, rather than running on every node in an Elasticsearch cluster. For instance, it could be implemented as a plugin to Logstash where you could specify how many workers you want to dedicate to this process.  

Thanks for the idea, but I'd suggest opening this on the Logstash issues list instead.
