### ISSUE TITLE
Logging on upgrade API

### ISSUE THREAD

**Issue by ppf2** [elasticsearch/elasticsearch#9227]
Currently, when you run the upgrade API, there is no logging to indicate when it started, what it is doing (not even at higher logging levels like DEBUG) and when it has completed.  It will be nice to provide some logging for this api.

**Comment by rjernst** [comment]
It looks like we should have some *minimal* logging in the merge policy that does the upgrade.  At DEBUG level, you should see messages like `Adding segment XYZ to be upgraded`.

I will add a message for each index/shard when it is beginning the upgrade.  However, when it ends is a little ambiguous.  The current code calls `waitForMerges` (through a hack, because this method is no longer public on `IndexWriter`).  Really what we want is to wait for the chain of `findForcedMerges` to complete.  I can add a log message when we are "done" here, but it is not necessarily correct (could log after the real upgrade finished).
