### ISSUE TITLE
Help needed for index field mapping after index creation

### ISSUE THREAD

**Issue by bvnagaraju** [elasticsearch/elasticsearch#9257]
Hi ,

we have a scenario where we know set of fields that we need at the time of index creation .This we know how do create field mapping at time of index creation .

But ,
we have other scenario where users can create custom fields after index creation .

Not sure how to do it .? If you can help with us sample code , it will be big help .

Also interested knowing thoughts on document schema this case

**Comment by dadoonet** [comment]
Hi,

You should better ask on the mailing for question. We could help you in a better way than here because this space is reserved for issues and feature requests.

That said, I believe you should look at http://www.elasticsearch.org/guide/en/elasticsearch/reference/current/indices-templates.html#indices-templates

Closing as it's not an issue. Feel free to reopen if you think it is.

**Comment by bvnagaraju** [comment]
can you point me to mailing ?please Thank you

**Comment by dadoonet** [comment]
http://www.elasticsearch.org/help
