### ISSUE TITLE
Update Joda to 2.7

### ISSUE THREAD

**Issue by dadoonet** [elasticsearch/elasticsearch#9338]
In elasticsearch, we are still using a old Joda version (2.3): 

```xml
<dependency>
    <groupId>joda-time</groupId>
    <artifactId>joda-time</artifactId>
    <!-- joda 2.0 moved to using volatile fields for datetime -->
    <!-- When updating to a new version, make sure to update our copy of BaseDateTime -->
    <version>2.3</version>
    <scope>compile</scope>
</dependency>
<dependency>
    <groupId>org.joda</groupId>
    <artifactId>joda-convert</artifactId>
    <version>1.2</version>
    <scope>compile</scope>
</dependency>
```

Joda released [version 2.7](https://github.com/JodaOrg/joda-time/releases) so we could may be upgrade?

```xml
<dependency>
  <groupId>joda-time</groupId>
  <artifactId>joda-time</artifactId>
  <version>2.7</version>
</dependency>
```

Reported in the mailing list: https://groups.google.com/d/msgid/elasticsearch/53e5872d-4f36-4c73-ac19-e806c761771f%40googlegroups.com?utm_medium=email&utm_source=footer

**Comment by clintongormley** [comment]
@dadoonet we probably should - just check the changelog before doing so.

**Comment by v1ctor** [comment]
Hi!
Could you please tell me when this enhancement will be in production?
Thanks!

**Comment by kimchy** [comment]
@dadoonet just note that we cary our own version of: https://github.com/elasticsearch/elasticsearch/blob/master/src/main/java/org/joda/time/base/BaseDateTime.java, so we need to copy it over from the new version, this is because of: https://github.com/elasticsearch/elasticsearch/blob/master/src/main/java/org/joda/time/base/BaseDateTime.java#L57
