### ISSUE TITLE
Incorrect query string AND OR parsing

### ISSUE THREAD

**Issue by zarucki** [elasticsearch/elasticsearch#9414]
First setup, because it seems that validation API requires index. I created index according to http://www.elasticsearch.org/guide/en/elasticsearch/reference/current/indices-create-index.html#mappings
```
curl -XPOST localhost:9200/test -d '{
  "settings" : {
    "number_of_shards" : 1
  },
  "mappings" : {
    "type1" : {
      "_source" : { "enabled" : false },
      "properties" : {
        "field1" : { "type" : "string", "index" : "not_analyzed" }
      }
    }
  }
}'
```
Now the problem. Executing this:
```
curl -XGET -o - 'http://localhost:9200/test/_validate/query?explain&pretty' -d'
{
    "query": {
    "bool": {
        "must": [ {
            "query_string": {
                "default_field": "_all",
                "query": "_all:(a AND b OR c AND d)"
            }
        } ]
    }
  }
}
'
```
returns:
```
{
  "valid" : true,
  "_shards" : {
    "total" : 1,
    "successful" : 1,
    "failed" : 0
  },
  "explanations" : [ {
    "index" : "test",
    "valid" : true,
    "explanation" : "+(+_all:a +_all:b +_all:c +_all:d)"
  } ]
}
```
As we can see OR condition was completely removed. The result is identical to the one we would get if we executed this with query string equal to "_all:(a AND b AND c AND d)".

Taking into account priorities I would expect it should return similar to following:
```
curl -XGET -o - 'http://localhost:9200/test/_validate/query?explain&pretty' -d'
{
  "query": {
    "bool": {
      "must": [ {
        "query_string": {
          "default_field": "_all",
          "query": "_all:((a AND b) OR (c AND d))"
        }
      } ]
    }
  }
}
'
```

which returns:
```
{
  "valid" : true,
  "_shards" : {
    "total" : 1,
    "successful" : 1,
    "failed" : 0
  },
  "explanations" : [ {
    "index" : "test",
    "valid" : true,
    "explanation" : "+((+_all:a +_all:b) (+_all:c +_all:d))"
  } ]
}
```

Somehow in the first example OR condition is lost. It's not only the validate or explain API. It seems that this also reflects how query strings are interpreted and executed.

"_all:(a OR b AND c)" case also returns strange results:
```
{
  "valid" : true,
  "_shards" : {
    "total" : 1,
    "successful" : 1,
    "failed" : 0
  },
  "explanations" : [ {
    "index" : "test",
    "valid" : true,
    "explanation" : "+(_all:a +_all:b +_all:c)"
  } ]
}
```
a condition is optional but nothing else is.

Tested this on just built master.

**Comment by clintongormley** [comment]
Yes :)

We use the classic query parser syntax straight out of Lucene, and what you are describing is a known limitation.  It is worth reading this excellent blog post discussing the foibles of the query string syntax: https://lucidworks.com/blog/why-not-and-or-and-not/

In particular, note these two rules:

* AND will change the Occurs flag of the clause to it’s left to MUST unless it has already been set to MUST_NOT
* AND sets the Occurs flag of the clause to it’s right to MUST

... and the recommendation to use parentheses rather than relying on operator precedence.

You're welcome to take this up with Lucene, where it would have to be changed in order to make it into Elasticsearch.
