### ISSUE TITLE
Elasticsearch accepts invalid json as input, then returns it invalid too

### ISSUE THREAD

**Issue by SjonHortensius** [elasticsearch/elasticsearch#9415]
Obviously I made a mistake when inserting the data; but I'd expected elasticsearch to tell me when my input is invalid. Testcase (notice the trailing closing **}** in the data):

```bash
curl -XPUT http://localhost:9200/test/hit/1 -d '{ "test":[1] }}'
# {"_index":"test","_type":"hit","_id":"1","_version":1,"created":true}

curl -XGET http://localhost:9200/test/hit/_search?pretty=1|json_verify
# JSON is invalid
```

Fwiw; e/s returns:

```json
{
  "took" : 7,
  "timed_out" : false,
  "_shards" : {
    "total" : 5,
    "successful" : 5,
    "failed" : 0
  },
  "hits" : {
    "total" : 1,
    "max_score" : 1.0,
    "hits" : [ {
      "_index" : "test",
      "_type" : "hit",
      "_id" : "1",
      "_score" : 1.0,
      "_source":{"test":[1]}}
    } ]
  }
}
```

I actually have some data inserted like this and everything seems to work fine. Can I correct this without reindexing everything? This is elasticsearch 1.4.2 running on Archlinux

**Comment by clintongormley** [comment]
Hi @SjonHortensius 

Yes - Elasticsearch is quite lenient about parsing invalid JSON, and it just returns the original JSON string when you search or GET a document.  We have a ticket open for improving this situation (see #2315).

> Can I correct this without reindexing everything?

No.  Whatever approach you take, you need to store a new _source string, which means reindexing everything.  What you could do is to use scan/scroll (with _source: false, so that you don't get the bad JSON returned to you) to return the id of every document in your index, tranche by tranche.  Then for each ID, issue an update statement for each document, which makes no changes, eg:

    curl -XPOST "http://localhost:9200/test/hit/1/_update" -d'
    {"doc":{}}'

This will rewrite the _source field, hopefully correcting your error

**Comment by SjonHortensius** [comment]
Thanks for the explanation. If this situation isn't expected it might be good if this were documented somewhere. It took me a few hours to find why Kibana broke, complaining about unparsable json. I'd never expected my own invalid input to be accepted while it was actually invalid :)
