### ISSUE TITLE
ES "Realocate" shards when only one node is running (it causes unnasigned shards)

### ISSUE THREAD

**Issue by fernandorodriguez** [elasticsearch/elasticsearch#9450]
Hi,
I was running a local node of ES (V 1.4) and this log appeared to me: 
high disk watermark [10%] exceeded on [vjAu_bJWTNyJjQX47cHdDg][Kormok] free: 37.5gb[8%], shards will be relocated away from this node

That relocate causes unnasigned shards because there is not another node available
37.5gb free is enough for me (I dont know if is right to taking percentajes)

disabling rebalance obviusly  makes it work again

thanks!!

**Comment by clintongormley** [comment]
Hi @fernandorodriguez 

It won't actually move shards unless it has somewhere to put them, so it won't cause unassigned shards. (I tested this out locally). With one node you will have unassigned replicas anyway, but the primaries won't be moved.  

> 37.5gb free is enough for me (I dont know if is right to taking percentajes)

You can change these settings to whatever works for you, including absolute values instead of percentages.  We just use 10% as the default.
