### ISSUE TITLE
Virtual alias fields for users to query / Real support for field aliasing

### ISSUE THREAD

**Issue by mgolinelli** [elasticsearch/elasticsearch#9453]
- Provide "virtual alias fields" for users to query using lucene Extendable QueryParser for example.
http://lucene.apache.org/core/4_2_0/queryparser/index.html
http://wiki.apache.org/solr/ExtendedDisMax#Field_aliasing_.2F_renaming

- Real field aliasing support

Benefits is not really clear to "capture" anyway,

Sincerely Yours

**Comment by clintongormley** [comment]
Hi @mgolinelli 

We don't support the edismax parser and we are unlikely to add it.  In fact we only recommend exposing the query_string query to expert users, not least of all because the syntax is confusing, fragile, and can produce very heavy queries.

Our recommendation is that the application should parse the user's input and generate the appropriate query DSL, rather than just exposing all of the features of the query_string query.

With this in mind, field aliases are easy to incorporate into that process (eg using a `multi_match` query).  I don't think we should add support for them in our API.

thanks
