### ISSUE TITLE
[GEO] Make sure jts dependency is optional for geo_point types

### ISSUE THREAD

**Issue by javanna** [elasticsearch/elasticsearch#9462]
jts dependency is currently optional in our maven pom, but `GeoPoint` depends on it at the moment (after https://github.com/elasticsearch/elasticsearch/commit/06667c6aa898895acd624b8a71a6e00ff7ae32b8). We should change this and restore `GeoPoint` to not depend on jts, so that the dependency is effectively optional.

**Comment by dadoonet** [comment]
+1

**Comment by nknize** [comment]
++1  

For bookkeeping I'm linking this issue with PR #9339  

History: ```GeoPolygonFilter``` for ```geo_point``` types do not handle pole and dateline wrapping correctly.  I corrected this issue in #8672 for ```geo_shape``` type but it relies on JTS (which is fine for ```geo_shape``` since the ShapeModule is optional).  Many users rely on ```geo_point``` type's ```GeoPolygonFilter``` which suffers from the same ambiguous polygon problem. This was reported in #5968.  PR #9339 corrects the issue but introduces this JTS dependency.  Will submit a new PR linked to this issue that eliminates the JTS dependency.

**Comment by javanna** [comment]
@nknize I think this was solved right? Can we close or is there still work in progress to fix the issue?

**Comment by nknize** [comment]
This issue was solved. Thanks for the reminder.
