### ISSUE TITLE
Exist filter not working when field name is same as _type name

### ISSUE THREAD

**Issue by petard** [elasticsearch/elasticsearch#9478]
When running the query example on the field `url` it will return 24 documents. However, running the same query on the field `event` returns 0 documents. Both fields have the same mapping `string, not analyzed`.

Really clueless why the results are different, since mapping is exactly the same and the fields are present in the same documents. Both fields are added to the index using a dynamic mapping that sets all strings to `string, not analyzed`.

Any reason why the number of returned documents differ?

Examples:

Query
```json
GET myindex_v1/_search
{
  "filter":{
    "exists": {
      "field": "url"
    }
  },
  "query": {
    "match_all": {}
  }
}
```

Document
```json
{
            "_index": "myindex_v1",
            "_type": "event",
            "_id": "ue3FNMV3SdSA4yQRcnmcrA",
            "_score": 1,
            "_source": {
               "bid": 2961926546,
               "event": "pageview",
               "payload": {
                  "new_user": 1,
                  "pageType": "product",
                  "price": 2244,
                  "product_id": 318046,
               },
               "url": "http://abc.html",
            }
         }
```

**Comment by jpountz** [comment]
Hi @petard,

Unfortunately, this is a side-effect of the fact that Elasticsearch allows to prepend types to field names, see https://github.com/elasticsearch/elasticsearch/issues/8872. What happens here is that "event" is interpreted as a type, and our field resolution resolves it to the root of the json object. And since elasticsearch does not index objects (only actual fields), when you search on an object, it internally translates `"exists": "my_object"` to `"exists": "my_object.*"` in order to match fields. So in your case elasticsearch searches for documents that have a field that starts with `.`, and none of them does.

This will hopefully be fixed when #8872 is fixed.
