### ISSUE TITLE
Timeout in elastic search

### ISSUE THREAD

**Issue by ashutoshbansal987** [elasticsearch/elasticsearch#9504]
Hi,

I am getting blank page on every 7th-8th consecutive search when I try to search any keyword back to back 50-60 times. The blank page occurs once the search times out. Can anyone suggest any possible cause for this and the solution to resolve this?

thanks in advance.

**Comment by ashutoshbansal987** [comment]
Hi,
Anyone who wanna help?

**Comment by markwalkom** [comment]
Are you searching in Kibana, and if so what version?

**Comment by ashutoshbansal987** [comment]
I use elastic search in a web app. When I search some keyword in the web app UI back to back 50-60 times I get this error. I am using elastic search-1.2.1
For management I use Marvel.

**Comment by clintongormley** [comment]
Hi @ashutoshbansal987 

It sounds like you are having slow garbage collections, presumably because your swap/memory settings are not correct.  Please look at this documentation: http://www.elasticsearch.org/guide/en/elasticsearch/reference/current/setup-configuration.html#setup-configuration-memory

For follow up questions, I suggest you try the mailing list first.
thanks
