### ISSUE TITLE
Shards stuck after deleting & recreating index

### ISSUE THREAD

**Issue by demon** [elasticsearch/elasticsearch#9604]
This is a test environment that has 4 nodes, all are master eligible. I need to reimage them all with a new partition scheme, so I took the first node offline for reinstall.

Cluster state was then red as 2 indexes had primary shards they couldn't allocate. Fair enough, it's all test data and can rebuild. Dropped the indexes and the unallocated shards disappeared. Cluster back to green.

Recreated the indexes but the old shards showed back up again and put the cluster back into red. At this point I tried to force allocate them. Doing that results in:

```
ElasticsearchIllegalArgumentException[[allocate] allocation of [enwiki_general_first][6] on node [deployment-elastic05][wSPDvi8cRDWOvfgXcnvm6w][deployment-elastic05][inet[/10.68.17.179:9300]]{master=true} is not allowed, reason: [NO(shard cannot be allocated on same node [wSPDvi8cRDWOvfgXcnvm6w] it already exists on)][YES(node passes include/exclude/require filters)][YES(primary is already active)][YES(below shard recovery limit of [2])][YES(allocation disabling is ignored)][YES(allocation disabling is ignored)][YES(no allocation awareness enabled)][YES(total shard limit disabled: [-1] <= 0)][YES(target node version [1.3.7] is same or newer than source node version [1.3.7])][YES(enough disk for shard on node, free: [56.4gb])][YES(shard not primary or relocation disabled)]]
```

I figured this means that it wasn't able to allocate the shard because such a shard exists already. I thought I'd outsmart things by dropping the index again and trying to allocate when there was no such index. No dice :(

```
ElasticsearchIllegalArgumentException[[allocate] failed to find [enwiki_general_first][6] on the list of unassigned shards]
```

At this point I knew we have some pretty messed up shards stuck somewhere. Thinking it was stuck in memory, I did a full cluster shutdown of all 4 nodes. After bringing them back up, the phantom shards still exist.

It's ultimately all test data so I could just nuke /var/lib/elasticsearch and start over but I'm more curious if there's a way out in case something so sinister happened to a production install. Or if there's any underlying bug here.

**Comment by nik9000** [comment]
Now that I think of it you might want to check  ```total_shards_per_node```.  In [production](http://en.wikipedia.org/w/api.php?action=cirrus-settings-dump&srbackend=CirrusSearch&format=json) enwiki_general has that set to 2.  So what you might be seeing is that setting leaking into your environment.  In that case it'd _look_ like the shards were phantom - they would reappear as soon as you made them and Elasticsearch wouldn't be able to assign them.  When I check [beta](http://en.wikipedia.beta.wmflabs.org/w/api.php?action=cirrus-settings-dump&format=json) it looks like it has that set to -1 but I can't be sure something isn't fishy.

**Comment by clintongormley** [comment]
The `total_shards_per_node` setting is dangerous, because it is an absolute setting, while the other allocation settings provide preferences.  

You don't mention how many replicas were configured?  If you had any replicas then, when you shut down one node, the replicas should have been promoted to primaries.  Presumably you had replicas set to zero, which is why your cluster went red instead of yellow.

Then you deleted the index (removing the remaining primary shards) and restarted the node, which caused the dangling primaries to be reimported.  But of course you were missing some primaries (because you deleted the index), so the index went red.

You haven't provided the cluster state, or the command you used to reroute shards, so it is difficult to figure out if you did something reasonable, or tried to allocate primary shards back to the nodes where they were already allocated (which is what the exception seems to indicate).

Could you provide more info, eg the settings you're using, the output of `GET _cat/shards?v` at each step, the reroute command you used, the cluster health (`?level=shards`) etc
