### ISSUE TITLE
significant_terms should provide a simple percentage scoring heuristic

### ISSUE THREAD

**Issue by jarib** [elasticsearch/elasticsearch#9720]
As discussed with @markharwood on the [mailing list](https://groups.google.com/d/msg/elasticsearch/1ojltqSRdhA/7tvVKKNTWe4J), it would be nice if `significant_terms` provided a scoring heuristic that is simply `doc_count` divided by `bg_count`.

In some contexts, scoring needs to be easy to explain to users, and percentages are something most of us can understand.

**Comment by markharwood** [comment]
Thanks for opening this.
I discussed this with @brwe and she reminded me of https://github.com/elasticsearch/elasticsearch/pull/7850 which is in development and adds the ability for custom scripts to perform scoring.

**Comment by markharwood** [comment]
Having implemented this it is worth sharing some feedback on the quality from tests with real data.
I opted to recreate your "top countries for 'foo' " scenario using a sample of 1m tweets where I looked at spoken language rather than country and "android" clients rather than "foo".

Here are the top 5 languages tweeting with Android devices using the straight percentage score you wanted: 
<table><tr><th>Language code</th><th>Android-sourced tweets vs all Tweets</th><th>Percentage Score</th></tr><tr><td align='center'>ps</td><td align='center'>3/5</td><td>0.6</td></tr><tr><td align='center'>hi</td><td align='center'>285/544</td><td>0.52</td></tr><tr><td align='center'>si</td><td align='center'>5/10</td><td>0.5</td></tr><tr><td align='center'>ko</td><td align='center'>9646/20448</td><td>0.47</td></tr><tr><td align='center'>ne</td><td align='center'>65/138</td><td>0.47</td></tr></table>

Some pretty obscure stuff in there, no?
Pashto, Nepalese and Slovene.
In many cases you would likely take a business decision to ignore terms with very low frequency.

For comparison, here are the top 5 results for the same query using the default significant_terms heuristic:
<table><tr><th>Language code</th><th>Android-sourced tweets vs all Tweets</th><th>Percentage Score</th></tr><tr><td align='center'>es</td><td align='center'>36821/112667</td><td>0.32</td></tr><tr><td align='center'>in</td><td align='center'>16041/42639</td><td>0.37</td></tr><tr><td align='center'>ko</td><td align='center'>9646/20448</td><td>0.47</td></tr><tr><td align='center'>pt</td><td align='center'>19847/60211</td><td>0.32</td></tr><tr><td align='center'>tl</td><td align='center'>4807/12951</td><td>0.37</td></tr></table>

Note it has automatically done what you would typically do to tweak the `percentage` heuristic - take the magnitude of the term into account as part of selection. The difference is you would pick a hard frequency threshold whereas the default heuristic has an in-built normalizing function that would still allow low-frequency items through in the absence of any better signals. I've omitted the actual scores used for ranking but you can see that the percentages are still high and the languages are not too obscure either. Both heuristics avoided selecting the most popular language, English because that appears to be skewed towards iPhone users rather than Android (something perhaps to do with correlations with English-speakers, affluence and willingness to "pay the Apple tax" for higher priced devices?).

In fact we can visualize the scoring logic used by these two heuristics:

The `percentage` heuristic tends to single out the rare languages found in the very bottom left of this popularity chart:

![query template-1](https://cloud.githubusercontent.com/assets/170925/6270125/a1511e24-b84f-11e4-8f72-0b51a3a6447a.jpg)

Whereas the default `JLH` heuristic looks for languages that have moved a fair way north of the diagonal "normal expectation" line, with allowance for the relative ease with which rarer terms can double in popularity:

![query template](https://cloud.githubusercontent.com/assets/170925/6270103/79de15ea-b84f-11e4-9fc0-2386ebb282c4.jpg)


### Summary
Use this new heuristic with caution - it likes really rare stuff.

**Comment by jarib** [comment]
Thanks for the explanation. I like the championship example in the docs as well.
