### ISSUE TITLE
support sorting in aliases

### ISSUE THREAD

**Issue by bhenderson** [elasticsearch/elasticsearch#9803]
Would it be possible to support a sort option in an alias.

My problem is that I have a sequence id in my index and I want my clients to default sort by that id.

thanks,

**Comment by clintongormley** [comment]
Hi @bhenderson 

While yes, it would be possible, I don't like the idea of adding this complexity to aliases.  The options available in aliases are intended for enforcing rules to give the illusion of multi-tenancy in a shared index.

A default sort is just a preference (one of many that could be requested) and then raises the question of eg what happens if the user specifies another sort order? should it be allowed or denied? What if they want to apply a secondary sort etc. And who knows what other use-case specific configurations could be requested?

This feels like it should be applied in a proxy layer in front of Elasticsearch instead.
