### ISSUE TITLE
Modify default shard allocation algorithm to use index for primary only indexes

### ISSUE THREAD

**Issue by tnine** [elasticsearch/elasticsearch#9829]
By default, primary shard allocation does not account for an index, only the number of primaries and replicas per node.  This does not cause even load in the following scenario.

1. Allocate 2 indexes, with primary shards only (0 replicas) across a cluster equal to the node count.  I.E 3 nodes, 3 shards.
1. Index 1 receives very little load
1. Index 2 receives very heavy load

In the current scenario, primary shards are not allocated evenly across nodes within an index.  In the primary shard only scenario above, this leads to uneven load distribution across the cluster.  Nodes should own an even, or as close to even distribution of primary shards as possible when no replicas are present.

**Comment by nik9000** [comment]
The simplest way to resolve this is to set ```index.routing.allocation.total_shards_per_node``` to 1 on high load indexes so that their shards are distributed evenly.  Its probably better than some fancy weighting algorithms because its pretty simple and creates a hard and fast rule.  My cluster has ~1800 indexes and only about 20 of them produce enough load that I set this on them.  It works well.

**Comment by tnine** [comment]
Awesome, so we need to set this per index then?  Thank you for your help!  Closing the issue
