### ISSUE TITLE
Global Settings/Mapping for an Index - not_analyzed and whitespace

### ISSUE THREAD

**Issue by MKA-MKA** [elasticsearch/elasticsearch#9987]
Hello, 
I want to globally set the following for all current string fields and future(new) string fields on an Index while creating that Index.   Thanks. Mka

"index": "not_analyzed", 
"analyzer":"whitespace"

**Comment by johtani** [comment]
Hi,

You should better ask on the mailing for question. We could help you in a better way than here because this space is reserved for issues and feature requests.
Mailing list is here. http://www.elasticsearch.org/help

That said, I believe you should look at http://www.elasticsearch.org/guide/en/elasticsearch/reference/current/indices-templates.html#indices-templates
And
http://www.elasticsearch.org/guide/en/elasticsearch/reference/current/mapping-root-object-type.html#_dynamic_templates

Closing as it's not an issue. Feel free to reopen if you think it is.
